config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'inventory/products#index'
  devise_for :users

  namespace :inventory do
    resources :products
    resources :carts, only: %i[show update]
    resources :purchases, only: %i[index show new create destroy]
    resources :tags, only: %i[index new create destroy]
    resources :product_tags, only: %i[create]
    resources :users, only: %i[show]
    resources :user_reviews
  end

  namespace :store do
    resources :likes, only: %i[new create destroy]
    resources :comments, only: %i[new create]
  end

  namespace :api do
    namespace :v1 do
      resources :authentication, param: :_username
      post '/auth/login', to: 'authentication#login'
      namespace :customers do
        resources :likes, only: %i[create]
        resources :purchases, only: %i[index create]
        resources :products, only: %i[index]
        get '/*a', to: 'application#not_found'
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

# The product model have four attributes
# 1. Name
# 2. Price
# 3. Stock
# 4. Description
# Every attribute has his validation
# The class have a scope method for update the product stock after a purchase

class Product < ApplicationRecord
  has_many :purchases
  has_many :carts, through: :purchases
  has_many :likes
  has_many :product_tags
  has_many :price_changes
  has_many :tags, through: :product_tags
  has_many :users, through: :likes
  has_many :comments, as: :commented
  has_one_attached :picture

  # Update the stock of the buyed products
  scope :buy_product, lambda { |product_id, new_stock|
    find_by(id: product_id).update(stock: new_stock)
  }
end

app/controllers/api/v1/customers/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Customers
      # Controller to allow acces to list products
      # order -> Only accept 'asc' o 'desc'
      # attribute -> Only accept 'name' o 'popularity'
      # filter_tag -> String
      # page -> Only accept integer and depend on how much products are
      # size -> Only accept integer
      class ProductsController < ApplicationController
        def index
          render json: Products::List.call(products_params), status: :ok
        end

        private

        def products_params
          params.permit(:order, :filter_tag, :attribute, :page, :size)
        end
      end
    end
  end
end

app/controllers/inventory/application_controller.rb
# frozen_string_literal: true

# Inherits from the main Application controller and have protected method to filter types of users

module Inventory
  class ApplicationController < ApplicationController
  end
end

app/controllers/inventory/carts_controller.rb
# frozen_string_literal: true

module Inventory
  # Products actions are limited by user type, only customer can make this actions
  class CartsController < ApplicationController
    before_action :authenticate_user!
    before_action :its_customer?

    def show
      @cart = Carts::Show.call(cart_params[:id])
    end

    def update
      cart = Carts::Pay.call(cart_params)
      redirect_to inventory_products_path, notice: cart
    end

    private

    def cart_params
      params.permit(:id, :total)
    end
  end
end

app/controllers/inventory/product_tags_controller.rb
# frozen_string_literal: true

module Inventory
  # Product tag controller dont have a view
  class ProductTagsController < ApplicationController
    before_action :authenticate_user!
    before_action :its_admin?
    # Check if the product had the tag and if not, add the tag to the product
    def create
      product_tag = ProductTags::AssignTag.call(product_tag_params)
      redirect_to inventory_products_path, notice: product_tag
    end

    private

    def product_tag_params
      params.permit(:tag_id, :product_id)
    end
  end
end

app/controllers/inventory/products_controller.rb
# frozen_string_literal: true

require 'json'
module Inventory
  # Products actions are limited by user type
  class ProductsController < Inventory::ApplicationController
    include Pagy::Backend
    before_action :authenticate_user!, except: %i[index show]
    before_action :its_admin?, except: %i[index show]

    def index
      @pagy, @products = pagy(Products::ProductQuery.new.products)
    end

    def show
      @product = Products::ShowQuery.new.find_by_user(params[:id])
      @purchase = Purchase.new
    end

    def new
      @product = Product.new
    end

    def create
      product = Products::Add.call(name: params[:product][:name], price: params[:product][:price],
                                   stock: params[:product][:stock], description: params[:product][:description],
                                   picture: params[:product][:picture])
      redirect_to inventory_products_path, notice: product
    end

    def edit
      @product = Product.find_by(id: params[:id])
    end

    def update
      product = Products::Modify.call(product_id: params[:id], stock: params[:stock], price: params[:price])
      redirect_to inventory_product_path, notice: product
    end

    def destroy
      product = Products::Delete.call(params[:id])
      redirect_to inventory_products_path, notice: product
    end

    private

    def product_params
      params.permit(:id, :name, :price, :stock, :description, :picture)
    end
  end
end

app/controllers/inventory/purchases_controller.rb
# frozen_string_literal: true

module Inventory
  # Products actions are limited by logged users
  class PurchasesController < ApplicationController
    before_action :authenticate_user!

    # The @purchase query make diferent joins if its a admin or a customer
    def index
      @purchases = Purchases::ListView.call(id: purchase_params[:id], user: current_user)
    end

    def show
      @purchase = Purchase.find_by(id: params[:id])
    end

    def new
      @purchase = Purchase.new
    end

    def create
      purchase = Purchases::AddToCartView.call(product_id: purchase_params[:product_id],
                                               quantity: purchase_params[:quantity], user_id: current_user.id)
      redirect_to inventory_products_path, notice: purchase
    end

    def destroy
      purchase = Purchases::Delete.call(purchase_params)
      redirect_to inventory_products_path, notice: purchase
    end

    private

    def purchase_params
      params.permit(:id, :product_id, :user_id, :quantity)
    end
  end
end

app/controllers/inventory/tags_controller.rb
# frozen_string_literal: true

module Inventory
  # Tags actions are limited for only admin use
  class TagsController < ApplicationController
    before_action :authenticate_user!
    before_action :its_admin?

    def index
      @tags = Tags::ReturnTags.call
    end

    def new
      @tag = Tag.new
    end

    # Tag_params its a filter who only permit tag_name as a parameter
    def create
      tag = Tags::Saver.call(tag_params)
      redirect_to inventory_tags_path, notice: tag
    end

    # Return a notice if the tag have a association restriction
    def destroy
      @tag = Tags::Delete.call(id: params[:id])
      redirect_to inventory_tags_path, notice: @tag
    end

    private

    def tag_params
      params.require(:tag).permit(:tag_name)
    end
  end
end

app/controllers/inventory/user_reviews_controller.rb
# frozen_string_literal: true

module Inventory
  # Admins can update and destroy reviews while the user only can created
  # Reviews need to be approved before be public
  class UserReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :its_customer?, only: %i[create]
    before_action :its_admin?, except: %i[index create]

    def index
      @reviews = UserReviews::UserReviewQuery.new.reviews
    end

    def update
      review = UserReviews::Approve.call(review_params)
      redirect_to inventory_user_reviews_path, notice: review
    end

    def create
      review = UserReviews::Review.call(review_params)
      redirect_to inventory_products_path, notice: review
    end

    def destroy
      review = UserReviews::Delete.call(review_params)
      redirect_to inventory_user_reviews_path, notice: review
    end

    private

    def review_params
      params.permit(:id, :reviewed_id, :reviewer_id, :review)
    end
  end
end

app/controllers/inventory/users_controller.rb
# frozen_string_literal: true

module Inventory
  # Only purpose is return a user info
  class UsersController < ApplicationController
    def show
      @user = User.find_by(id: params[:id])
    end
  end
end

app/helpers/api/products_helper.rb
# frozen_string_literal: true

module Api
  module ProductsHelper
  end
end

app/helpers/api/v1/customers/products_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module Customers
      module ProductsHelper
      end
    end
  end
end

app/helpers/inventory/price_changes_helper.rb
# frozen_string_literal: true

module Inventory
  module PriceChangesHelper
  end
end

app/helpers/inventory/product_add_helper.rb
# frozen_string_literal: true

module Inventory
  module ProductAddHelper
  end
end

app/helpers/inventory/product_tags_helper.rb
# frozen_string_literal: true

module Inventory
  module ProductTagsHelper
  end
end

app/helpers/inventory/purchases_helper.rb
# frozen_string_literal: true

module Inventory
  module PurchasesHelper
  end
end

app/helpers/inventory/tags_helper.rb
# frozen_string_literal: true

module Inventory
  module TagsHelper
  end
end

app/helpers/inventory/user_reviews_helper.rb
# frozen_string_literal: true

module Inventory
  module UserReviewsHelper
  end
end

app/helpers/inventory/users_helper.rb
# frozen_string_literal: true

module Inventory
  module UsersHelper
  end
end

app/helpers/product_helper.rb
# frozen_string_literal: true

module ProductHelper
end

app/views/inventory/products/_admin.html.erb
<div class="row space-left">
  <div class='col-md-1'>
    <h5> Filter by:</h5>
  </div>
  <div class='col-md-1'>
        <% if params[:order] == 'products.name desc' %>
           <%= link_to 'Name ↑', inventory_products_path(order: 'products.name asc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <% elsif params[:order] == 'products.name asc' %>
           <%= link_to 'Name ↓', inventory_products_path(order: 'products.name desc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <%else%>
          <%= link_to 'Name ↓', inventory_products_path(order: 'products.name desc'), class: "btn btn-outline-secondary" %>
          <% table_order = 'products.id asc' %>
        <% end %> 
  </div>
  <div class='col-md-1'>
      
        <% if params[:order] == 'popularity desc' %>
           <%= link_to 'Popularity ↑', inventory_products_path(order: 'popularity asc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <% elsif params[:order] == 'popularity asc' %>
           <%= link_to 'Popularity ↓', inventory_products_path(order: 'popularity desc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <% else %>
          <%= link_to 'Popularity ↓', inventory_products_path(order: 'popularity desc'), class: "btn btn-outline-secondary" %>
        <% end %>
  </div>
  <div class='col-md-5'></div>
  <div class='col-md-1'>
    <% if params.has_key?(:name_filter) %>
    <% filter = "tags.tag_name LIKE '%#{params[:name_filter]}%'" %>
    <%= link_to 'Clean search', inventory_products_path, class:'btn btn-warning' %>
    <% else %>
    <% filter = '' %>
    <% end %>
  </div>
  <div class='col-md-1'>
    
  </div>
  <div class='col-md-1'>
  <%= form_tag inventory_products_path, method: :get do %>
    <%= text_field_tag :name_filter %> <br> <br>
    <%= submit_tag 'Filter by tag', class: "btn btn-secondary" %> 
    <% end %>
  </div>
</div>

<hr class="my-4 space-left">

<div class='row space-left'> 

<% @products.order(table_order).where("#{filter}").each do |product|%>  
<div class='col-md-2 d-flex align-items-stretch top-space'>
  <div class="card" style="width: 18rem;">
  <% if product.picture.attached? %>
    <div> <%= image_tag product.picture, class: "card-img-top", height: '220px', width: '220px' %> </div>
  <% else %>
    <div> <%= image_tag 'product.jpg', class: "card-img-top", height: '220px', width: '220px' %> </div>
  <% end %>
    <div class="card-body">
      <h5 class="card-title"> <%= product.name %> </h5>
      <p class="card-text"> <%= product.description %> </p>
      <div class="row">
        <div class='col-md-6'>
          <h5> $<%= product.price %> </h5>
        </div>
        <div class='col-md-6'>
          <h5> Stock: <%= product.stock %> </h5>
      </div>
      
    </div>
    
  </div>
  <div class='row'>
    <div class='col-sm-1'></div>
    <div class='col-sm-4'>
      <%= link_to 'Details', inventory_product_path(product.id.to_i), class: 'btn btn-secondary' %>
    </div>
    <div class='col-sm-1'></div>
    <div class='col-sm-4'>
      <b> Likes: <%= product.popularity %> </b>
    </div>
  </div>
  <p></p>
  </div><br>
</div>

<% end %>
</div>
<br><br>
<div class='row'>
  <div class='col-md-5'></div>
  <div class='col-md-4'>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/inventory/products/_customer.html.erb
<div class="row space-left">
  <div class='col-md-1'>
    <h5> Filter by:</h5>
  </div>
  <div class='col-md-1'>
        <% if params[:order] == 'products.name desc' %>
           <%= link_to 'Name ↑', inventory_products_path(order: 'products.name asc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <% elsif params[:order] == 'products.name asc' %>
           <%= link_to 'Name ↓', inventory_products_path(order: 'products.name desc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <%else%>
          <%= link_to 'Name ↓', inventory_products_path(order: 'products.name desc'), class: "btn btn-outline-secondary" %>
          <% table_order = 'products.id asc' %>
        <% end %> 
  </div>
  <div class='col-md-1'>
      
        <% if params[:order] == 'popularity desc' %>
           <%= link_to 'Popularity ↑', inventory_products_path(order: 'popularity asc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <% elsif params[:order] == 'popularity asc' %>
           <%= link_to 'Popularity ↓', inventory_products_path(order: 'popularity desc'), class: "btn btn-outline-secondary" %>
           <% table_order = params[:order]%>
        <% else %>
          <%= link_to 'Popularity ↓', inventory_products_path(order: 'popularity desc'), class: "btn btn-outline-secondary" %>
        <% end %>
  </div>

  
  <div class='col-md-5'></div>
  <div class='col-md-1'>
  <% if params.has_key?(:name_filter) %>
  <% filter = "tags.tag_name LIKE '%#{params[:name_filter]}%'" %>
  <%= link_to 'Clean search', inventory_products_path, class:'btn btn-warning' %>
  <% else %>
  <% filter = '' %>
  <% end %>
  </div>
  <div class='col-md-1'>
    
  </div>
  <div class='col-md-1'>
    <%= form_tag inventory_products_path, method: :get do %>
    
    <%= text_field_tag :name_filter %> <br><br>
    <%= submit_tag 'Filter by tag', class: "btn btn-secondary" %> 
    <% end %>
  </div>
</div>
<hr class="my-4 space-left">

<div class='row space-left'> 

<% @products.order(table_order).where("#{filter}").each do |product|%>  
<div class='col-md-2 d-flex align-items-stretch top-space'>
  <div class="card" style="width: 18rem;">
  <% if product.picture.attached? %>
    <div> <%= image_tag product.picture, class: "card-img-top", height: '220px', width: '220px' %> </div>
  <% else %>
    <div> <%= image_tag 'product.jpg', class: "card-img-top", height: '220px', width: '220px' %> </div>
  <% end %>
    <div class="card-body">
      <h5 class="card-title"> <%= product.name %> </h5>
      <p class="card-text"> <%= product.description %> </p>
      <div class="row">
        <div class='col-md-6'>
          <h5> $<%= product.price %> </h5>
        </div>

        <div class='col-md-6'>
          <h5> Stock: <%= product.stock %> </h5>
      </div>
      
      
    </div>
    
  </div>
  <div class='row'>
    <div class='col-sm-1'></div>
    <div class='col-sm-3'>
      <%= link_to 'Details', inventory_product_path(product.id.to_i), class: 'btn btn-secondary' %>
    </div>
    <div class='col-sm-2'></div>
    <div class='col-sm-4'>
      <b> Likes: <%= product.popularity %> </b>
    </div>
  </div>
  <p></p>
  </div><br>
</div>

<% end %>
</div>
<br><br>
<div class='row'>
  <div class='col-md-5'></div>
  <div class='col-md-4'>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/inventory/products/_details.html.erb
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
<article class="col-lg-12" > 
  <div class="img-big-wrap">
  <% if @product.picture.attached? %>
    <div> <%= image_tag @product.picture.variant(resize_to_fit: [220, 220]), class: "card-img-top" %> </div>
  <% else %>
    <div> <%= image_tag 'product.jpg', class: "card-img-top" %> </div>
  <% end %>
</div>
</article>
		</aside>
		<aside class="col-sm-7">
<article class="card-body p-5">
	<h3 class="title mb-3"> <%= @product.name %> </h3>

<p class="price-detail-wrap"> 
	<span class="price h3 text-warning"> 
		<span class="currency">US $</span><span class="num"> <%= @product.price %>  </span>
	</span> 
</p>
<dl class="item-property">
  <dt>Description</dt>
  <dd><p> <%= @product.description %>  </p></dd>
</dl>
<dl class="item-property">
  <dt>Stock</dt>
  <dd><p> <%= @product.stock %>  </p></dd>
</dl>
<dl class="item-property">
  <dt>Tags</dt>
  <dd><% @product.tags.each do |tag| %>
      <p> <%= tag.tag_name %> </p>
      <% end %>
  </dd>
</dl>

<% @price_change = @product.price_changes.last %>
<% unless @price_change.nil? %>
<dl class="item-property">
  <dt>Last price:</dt>  
  <dd> <p> $<%= @price_change.old_price %> </p>
  </dd>
</dl>
<% end %>

<hr>



<%= form_with url: '/inventory/purchases', method: :post do |form| %>
  <%= form.label :quantity, "Quantity: "%>
  <%= form.hidden_field :product_id, value: @product.id %><br/><br/>
  <%= form.number_field :quantity, in: 1..@product.stock, value: 1, class: 'form-control' %> <br/>
  <%= form.submit 'Add to cart' %>
<% end %>
<br />
<div class='col-sm-3'>
      <% if Like.already_liked(current_user.id, @product.id).zero?%>
        <td>  <%= link_to '♡', store_likes_path(user_id: current_user.id, product_id: @product.id), method: :create, class: 'btn btn-outline-danger' %> </td>
      <% else %>
        <td>  <%= link_to '♥', store_like_path(user_id: current_user.id, product_id: @product.id), method: :delete, data: { confirm: 'Are you sure to unlike this produyct?' },  class: 'btn btn-danger' %> </td>
      <% end %>
    </div>
</article>
		</aside> 
	</div> 
 
</div> 
</div><br />

<div class="row">
<div class="col-md-6">
  <%= render partial: '/store/comments/form_coment', locals: {object: @product, type: 'product'} %>
</div>
  <div class="col-md-5">
    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Comment</th>
        <th scope="col">Rate</th>
      </tr>
    </thead>
    <tbody>
    <% @product.comments.each do |comment| %>
      <tr>
        <td> <%= link_to  User.find_by(id: comment.user_id).email, inventory_user_url(comment.user_id) %> </td>
        <td> <%= comment.description %> </td>
      </tr>
    <% end %>
      
    </tbody>
  </table>
  </div>
  
</div>

app/views/inventory/products/_details_admin.html.erb
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
<article class="col-lg-12" > 
  <div class="img-big-wrap">
  <% if @product.picture.attached? %>
    <div> <%= image_tag @product.picture.variant(resize_to_fit: [220, 220]), class: "card-img-top" %> </div>
  <% else %>
    <div> <%= image_tag 'product.jpg', class: "card-img-top" %> </div>
  <% end %>  
</div>
</article>
		</aside>
		<aside class="col-sm-7">
<article class="card-body p-5">
	<h3 class="title mb-3"> <%= @product.name %> </h3>

<p class="price-detail-wrap"> 
	<span class="price h3 text-warning"> 
		<span class="currency">US $</span><span class="num"> <%= @product.price %>  </span>
	</span> 
</p>
<dl class="item-property">
  <dt>Description</dt>
  <dd><p> <%= @product.description %>  </p></dd>
</dl>
<dl class="item-property">
  <dt>Stock</dt>
  <dd><p> <%= @product.stock %>  </p></dd>
</dl>
<dl class="item-property">
  <dt>Tags</dt>
  <dd><% @product.tags.each do |tag| %>
      <p> <%= tag.tag_name %> </p>
      <% end %>
  </dd>
</dl>
<% @price_change = @product.price_changes.last %>
<% unless @price_change.nil? %>
<dl class="item-property">
  <dt>Last price:</dt>  
  <dd> <p> $<%= @price_change.old_price %> </p>
  </dd>
</dl>
<% end %>
<hr>

<div class='row'>
  <div class='col-md-2'>
    <%= form_with url: inventory_product_tags_path, method: :post do |form| %>
    <%= form.hidden_field :product_id, value: @product.id %>
    <%= form.collection_select :tag_id, Tag.order(:tag_name),:id,:tag_name, include_blank: false  %><br/><br/>
    <%= form.submit 'Add tag', class: 'btn btn-success' %>
  <% end %>
  </div>
  
</div>
<hr>
<div class="row">
  <div class='col-md-2'>
    <%= link_to 'Delete product', inventory_product_path, method: :delete, class: 'btn btn-danger' %>
  </div>
  <div class='col-md-2'>
    <%= link_to 'Edit product', edit_inventory_product_path, class: 'btn btn-info' %>
  </div>
</div>

<br />
</article>
		</aside> 
	</div> 
</div> 
</div>
<div class="row">
<div class="col-md-5"></div>
  <div class="col-md-5">
    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Comment</th>
        <th scope="col">Rate</th>
      </tr>
    </thead>
    <tbody>
    <% @product.comments.each do |comment| %>
      <tr>
        <td> <%= User.find_by(id: comment.user_id).email %> </td>
        <td> <%= comment.description %> </td>
      </tr>
    <% end %>
      
    </tbody>
  </table>
  </div>
</div>

app/views/inventory/products/_details_xuser.html.erb
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
<article class="col-lg-12" > 
  <div class="img-big-wrap">
  <% if @product.picture.attached? %>
    <div> <%= image_tag @product.picture.variant(resize_to_fit: [220, 220]), class: "card-img-top" %> </div>
  <% else %>
    <div> <%= image_tag 'product.jpg', class: "card-img-top" %> </div>
  <% end %>
</div>
</article>
		</aside>
		<aside class="col-sm-7">
<article class="card-body p-5">
<% %>
	<h3 class="title mb-3"> <%= @product.name %> </h3>

<p class="price-detail-wrap"> 
	<span class="price h3 text-warning"> 
		<span class="currency">US $</span><span class="num"> <%= @product.price %>  </span>
	</span> 
</p>
<dl class="item-property">
  <dt>Description</dt>
  <dd><p> <%= @product.description %>  </p></dd>
</dl>
<dl class="item-property">
  <dt>Stock</dt>
  <dd><p> <%= @product.stock %>  </p></dd>
</dl>
<dl class="item-property">
  <dt>Tags</dt>
  <dd><% @product.tags.each do |tag| %>
      <p> <%= tag.tag_name %> </p>
      <% end %>
  </dd>
</dl>

<% @price_change = @product.price_changes.last %>
<% unless @price_change.nil? %>
<dl class="item-property">
  <dt>Last price:</dt>  
  <dd> <p> $<%= @price_change.old_price %> </p>
  </dd>
</dl>
<% end %>
</article>
		</aside> 
	</div> 
</div> 
</div>
<div class="row">
<div class="col-md-5"></div>
  <div class="col-md-5">
    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Comment</th>
        <th scope="col">Rate</th>
      </tr>
    </thead>
    <tbody>
    <% @product.comments.each do |comment| %>
      <tr>
        <td> <%= comment.user_id %> </td>
        <td> <%= comment.description %> </td>
      </tr>
    <% end %>
      
    </tbody>
  </table>
  </div>
</div>

app/views/inventory/products/_navbar_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Sivar Snack Store', inventory_products_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to 'Add Product', new_inventory_product_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tags', inventory_tags_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Purchases', inventory_purchases_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'User reviews', inventory_user_reviews_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class='navbar-nav ms-auto mb-2 mb-lg-0'>
        <li  class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
        </li>
      </ul>
    </div>
  </div>
</nav><br />

app/views/inventory/products/_navbar_customer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Sivar Snack Store', inventory_products_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class='navbar-nav ms-auto mb-2 mb-lg-0'>
      <li class="nav-item">
          <%= link_to 'Purchases', inventory_purchases_path, class: 'nav-link' %>
        </li>
        <li  class="nav-item">
        <% cart = Cart.has_cart_active(current_user.id).ids[0] %>
        <% unless cart.nil? %>
          <%= link_to "Cart", inventory_cart_path(cart), class: 'nav-link'  %>
        <% end %>
        </li>
        <li  class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
        </li>
      </ul>
    </div>
  </div>
</nav><br/>

app/views/inventory/products/edit.html.erb
<%= render partial: 'navbar_admin' %>
<%= render 'form_update', product: @product %>

app/views/inventory/products/index.html.erb
<% if current_user.nil? %>
  <%= render partial: 'navbar_xuser' %>
  <h2 id="notice"><%= notice %></h2>
  <%= render partial: 'xuser' %>
<% elsif current_user.user_type_id == 1%>
  <%= render partial: 'navbar_admin' %>
  <h2 id="notice"><%= notice %></h2>
  <%= render partial: 'admin' %>
<% elsif current_user.user_type_id == 2%>
  <%= render partial: 'navbar_customer' %>
  <h2 id="notice"><%= notice %></h2>
  <%= render partial: 'customer' %>
<% end %>